version: '3.1'

services:
  jedox:
    build: .
    ports:
      - 80:80
      - 7777:7777
      - 7775:7775
    privileged: true
    volumes:
      - ./installer:/tmp
      - ./data:/opt
    restart: always
    tty: true
